# debugging
CUDA_VISIBLE_DEVICES=2 python single_official_train.py --num_workers 4 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-3 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/dump

# img_baseline
CUDA_VISIBLE_DEVICES=2 python single_official_train.py --num_workers 4 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-3 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/img_baseline
CUDA_VISIBLE_DEVICES=3 python single_official_train.py --num_workers 4 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-3 --split_type puzzle --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/zeroshot/img_baseline

# Baseline hyper parameter tuning
CUDA_VISIBLE_DEVICES=0 python single_official_train.py --num_workers 4 --num_epochs 2 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-3 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/hypertune/hypertune1
CUDA_VISIBLE_DEVICES=1 python single_official_train.py --num_workers 4 --num_epochs 2 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-4 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/hypertune/hypertune2
CUDA_VISIBLE_DEVICES=2 python single_official_train.py --num_workers 4 --num_epochs 2 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-5 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/hypertune/hypertune3
CUDA_VISIBLE_DEVICES=3 python single_official_train.py --num_workers 4 --num_epochs 2 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-6 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/hypertune/hypertune4