# debugging
CUDA_VISIBLE_DEVICES=2 python single_official_train.py --num_workers 4 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-3 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/dump

# img_baseline
CUDA_VISIBLE_DEVICES=2 python single_official_train.py --num_workers 4 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-3 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/img_baseline
CUDA_VISIBLE_DEVICES=3 python single_official_train.py --num_workers 4 --model_name qwen2_vl_2b --num_epochs 1 --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-3 --split_type puzzle --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/zeroshot/img_baseline

# Baseline hyper parameter tuning
CUDA_VISIBLE_DEVICES=0 python single_official_train.py --num_workers 4 --num_epochs 5 --model_name qwen2_vl_2b --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-6 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/hypertune/hypertune1 --monolithic
CUDA_VISIBLE_DEVICES=1 python single_official_train.py --num_workers 4 --num_epochs 5 --model_name qwen2_vl_2b --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-7 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/hypertune/hypertune2 --monolithic
CUDA_VISIBLE_DEVICES=2 python single_official_train.py --num_workers 4 --num_epochs 5 --model_name qwen2_vl_2b --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-1 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/hypertune/hypertune3
CUDA_VISIBLE_DEVICES=3 python single_official_train.py --num_workers 4 --num_epochs 5 --model_name qwen2_vl_2b --loss_type classifier --batch_size 1 --log_freq 10 --train_backbone --word_embed bert --lr 1e-2 --puzzles all --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/hypertune/hypertune4

# On Air: qwen2_vl hidden_states 1,2,3 puzzle monolithic, 101head

CUDA_VISIBLE_DEVICES=2 python single_official_train.py --num_workers 4 --num_epochs 100 --model_name qwen2_vl_2b --loss_type classifier --batch_size 4 --log_freq 10 --train_backbone --word_embed bert --lr 1e-5 --puzzles 1,2,3 --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/qwen2_vl_hidden_states_101_head
CUDA_VISIBLE_DEVICES=2 python single_official_train.py --num_workers 4 --num_epochs 100 --model_name qwen2_vl_2b --loss_type classifier --batch_size 4 --log_freq 10 --train_backbone --word_embed bert --lr 1e-5 --puzzles 1,2,3 --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/qwen2_vl_hidden_states_101_head --test --seed 1339

CUDA_VISIBLE_DEVICES=3 python single_official_train.py --num_workers 4 --num_epochs 100 --model_name qwen2_vl_2b --loss_type classifier --batch_size 4 --log_freq 10 --train_backbone --word_embed bert --lr 1e-7 --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/qwen2_vl_hidden_states_supervised_dynamic_lr
CUDA_VISIBLE_DEVICES=3 python single_official_train.py --num_workers 4 --num_epochs 100 --model_name qwen2_vl_2b --loss_type classifier --batch_size 4 --log_freq 10 --train_backbone --word_embed bert --lr 1e-7 --split_type standard --save_root /data/jhpark_checkpoint/schema_and_argument_ckpt/official_classification/supervised/qwen2_vl_hidden_states_supervised_dynamic_lr --test --seed 4459
